name: Run clang-tidy

runs:
    using: composite

    steps:
      - name: Run clang-tidy
        # Vendored C code in contrib (LMDB) is not checked.
        run: run-clang-tidy-17 -q -p build -warnings-as-errors=\* '^(?!.*/contrib/)'
        shell: bash
